// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using document.lib.api;

namespace document.lib.api.Migrations
{
    [DbContext(typeof(DocumentlibContext))]
    [Migration("20190518123109_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("document.lib.api.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("Abbreviation");

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<DateTimeOffset>("LastUpdatedAt");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("document.lib.api.Models.DocumentTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<DateTimeOffset>("LastUpdatedAt");

                    b.Property<Guid>("LibDocumentId");

                    b.Property<Guid>("TagId");

                    b.HasKey("Id");

                    b.HasIndex("LibDocumentId");

                    b.HasIndex("TagId");

                    b.ToTable("DocumentTags");
                });

            modelBuilder.Entity("document.lib.api.Models.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<DateTimeOffset>("LastUpdatedAt");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("document.lib.api.Models.LibDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<Guid?>("CategoryId");

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<Guid?>("FolderId");

                    b.Property<DateTimeOffset>("LastUpdatedAt");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FolderId");

                    b.ToTable("LibDocuments");
                });

            modelBuilder.Entity("document.lib.api.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<DateTimeOffset>("LastUpdatedAt");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("document.lib.api.Models.DocumentTag", b =>
                {
                    b.HasOne("document.lib.api.Models.Tag", "Tag")
                        .WithMany("Documents")
                        .HasForeignKey("LibDocumentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("document.lib.api.Models.LibDocument", "LibDocument")
                        .WithMany("Tags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("document.lib.api.Models.LibDocument", b =>
                {
                    b.HasOne("document.lib.api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("document.lib.api.Models.Folder", "Folder")
                        .WithMany("Documents")
                        .HasForeignKey("FolderId");
                });
#pragma warning restore 612, 618
        }
    }
}
